### ISSUE TITLE
Events not firing to VB6

### ISSUE THREAD

**Issue by marco-manfroni** [janschreier/net6COMSample#1]
Nice article on how to make com interop work with .net6.
I wanted to test if it works with VB6 and it works!!! but...
I added an event to your demo, but these are only fired when I make a call from VB6 to a C# method that raise an event.
If I add a System.Timers.Timer that raise a C# event after few seconds and inside that event I raise a VB6 event, it doesnt fire and I have these errors (NotifyMessage is the name of the event to raise):

Exception:RFLCT.Targ_ITargMismatch
Exception Source:System.Private.CoreLib
Exception StackTrace:   at System.RuntimeType.InvokeDispMethod(String name, BindingFlags invokeAttr, Object target, Object[] args, Boolean[] byrefModifiers, Int32 culture, String[] namedParameters)
   at System.RuntimeType.InvokeMember(String name, BindingFlags bindingFlags, Binder binder, Object target, Object[] providedArgs, ParameterModifier[] modifiers, CultureInfo culture, String[] namedParams)
   at System.RuntimeType.ForwardCallToInvokeMember(String memberName, BindingFlags flags, Object target, Object[] aArgs, Boolean[] aArgsIsByRef, Int32[] aArgsWrapperTypes, Type[] aArgsTypes, Type retType)
   at Contract.IServerEvents.NotifyMessage(String message, Boolean isErrorMessage)
   at COMServer.Server.EventHandlerMessage.Invoke(String message, Boolean isErrorMessage)

Here you your demo file C# + VB6 where I added the events
[net6COMSample-main-events.zip](https://github.com/janschreier/net6COMSample/files/10216597/net6COMSample-main-events.zip)

BR
Marco

**Comment by janschreier** [comment]
hi Marco,
the whole stuff is still arcane mystery for me and i am working on getting rid of this interim solution right now. So I cannot really help you with that issue. as a workaround for your problem how about having a property in your c# code that is regularly checked by your vb6 code (as you do it already with the time) and if it has a certain value you take this as event?

not very elegantly but the solution we're working on here is far away from anything elegant anyway.

hope that helps!
